version: '3.8'
services:
  consul:
    image: art.behsacorp.com:5000/docker/channel/baseimage/hashicorp/consul:1.20.4
    container_name: consul
    restart: always
    volumes:
      - ./consul_data:/consul/data
      - ./consul_config:/consul/config
    ports:
      - "8500:8500"        # UI
      - "8600:8600/udp"    # DNS (UDP)
      - "8600:8600/tcp"    # DNS (TCP)
      - "8300:8300"        # Server RPC
      - "8301:8301"        # Serf LAN
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
    command: agent -server -bootstrap -ui -client=0.0.0.0 -data-dir=/consul/data -config-dir=/consul/config
    environment:
      - CONSUL_LOCAL_CONFIG={"acl":{"enabled":true, "default_policy":"deny", "down_policy":"extend-cache"}}
      - CONSUL_RETRY_JOIN_ADDRESS=178.18.63.42
      - CONSUL_GOSSIP_ENCRYPTION=enable
      - CONSUL_GOSSIP_ENCRYPTION_KEY=Mmqfj/p23iDGvBi1U6gE+WCr+dT+Fzm8+S2HcoVTB6c=
    networks:
      - consul-network

networks:
  consul-network:
    driver: bridge

volumes:
  consul_data:
  consul_config:
